#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-DEoptim
Version  : 2.2.6
Release  : 32
URL      : https://cran.r-project.org/src/contrib/DEoptim_2.2-6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/DEoptim_2.2-6.tar.gz
Summary  : Global Optimization by Differential Evolution
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-DEoptim-lib = %{version}-%{release}
BuildRequires : buildreq-R

%description
# DEoptim
`DEoptim` implements the Differential Evolution algorithm for global optimization of a real-valued function of a
real-valued parameter vector. The implementation of Differential Evolution in DEoptim interfaces with C
code for efficiency.  Moreover, the package is self-contained and does not depend on any other packages.

%package lib
Summary: lib components for the R-DEoptim package.
Group: Libraries

%description lib
lib components for the R-DEoptim package.


%prep
%setup -q -c -n DEoptim
cd %{_builddir}/DEoptim

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620226208

%install
export SOURCE_DATE_EPOCH=1620226208
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc DEoptim || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/DEoptim/CITATION
/usr/lib64/R/library/DEoptim/DESCRIPTION
/usr/lib64/R/library/DEoptim/INDEX
/usr/lib64/R/library/DEoptim/Meta/Rd.rds
/usr/lib64/R/library/DEoptim/Meta/data.rds
/usr/lib64/R/library/DEoptim/Meta/demo.rds
/usr/lib64/R/library/DEoptim/Meta/features.rds
/usr/lib64/R/library/DEoptim/Meta/hsearch.rds
/usr/lib64/R/library/DEoptim/Meta/links.rds
/usr/lib64/R/library/DEoptim/Meta/nsInfo.rds
/usr/lib64/R/library/DEoptim/Meta/package.rds
/usr/lib64/R/library/DEoptim/NAMESPACE
/usr/lib64/R/library/DEoptim/NEWS
/usr/lib64/R/library/DEoptim/R/DEoptim
/usr/lib64/R/library/DEoptim/R/DEoptim.rdb
/usr/lib64/R/library/DEoptim/R/DEoptim.rdx
/usr/lib64/R/library/DEoptim/data/SMI.rda
/usr/lib64/R/library/DEoptim/data/xrrData.rda
/usr/lib64/R/library/DEoptim/demo/DEoptim.R
/usr/lib64/R/library/DEoptim/demo/benchmarks.R
/usr/lib64/R/library/DEoptim/help/AnIndex
/usr/lib64/R/library/DEoptim/help/DEoptim.rdb
/usr/lib64/R/library/DEoptim/help/DEoptim.rdx
/usr/lib64/R/library/DEoptim/help/aliases.rds
/usr/lib64/R/library/DEoptim/help/paths.rds
/usr/lib64/R/library/DEoptim/html/00Index.html
/usr/lib64/R/library/DEoptim/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/DEoptim/libs/DEoptim.so
/usr/lib64/R/library/DEoptim/libs/DEoptim.so.avx2
/usr/lib64/R/library/DEoptim/libs/DEoptim.so.avx512
