#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-DEoptim
Version  : 2.2.4
Release  : 1
URL      : https://cran.r-project.org/src/contrib/DEoptim_2.2-4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/DEoptim_2.2-4.tar.gz
Summary  : Global Optimization by Differential Evolution
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-DEoptim-lib
Requires: R-colorspace
BuildRequires : R-colorspace
BuildRequires : clr-R-helpers

%description
DEoptim is an R implementation of the Differential Evolution
optimization algorithm.  It is still under development and is
distributed without warranty.

%package lib
Summary: lib components for the R-DEoptim package.
Group: Libraries

%description lib
lib components for the R-DEoptim package.


%prep
%setup -q -c -n DEoptim

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1521173333

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1521173333
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library DEoptim
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library DEoptim|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/DEoptim/CITATION
/usr/lib64/R/library/DEoptim/DESCRIPTION
/usr/lib64/R/library/DEoptim/INDEX
/usr/lib64/R/library/DEoptim/Meta/Rd.rds
/usr/lib64/R/library/DEoptim/Meta/data.rds
/usr/lib64/R/library/DEoptim/Meta/demo.rds
/usr/lib64/R/library/DEoptim/Meta/features.rds
/usr/lib64/R/library/DEoptim/Meta/hsearch.rds
/usr/lib64/R/library/DEoptim/Meta/links.rds
/usr/lib64/R/library/DEoptim/Meta/nsInfo.rds
/usr/lib64/R/library/DEoptim/Meta/package.rds
/usr/lib64/R/library/DEoptim/Meta/vignette.rds
/usr/lib64/R/library/DEoptim/NAMESPACE
/usr/lib64/R/library/DEoptim/NEWS
/usr/lib64/R/library/DEoptim/R/DEoptim
/usr/lib64/R/library/DEoptim/R/DEoptim.rdb
/usr/lib64/R/library/DEoptim/R/DEoptim.rdx
/usr/lib64/R/library/DEoptim/data/SMI.rda
/usr/lib64/R/library/DEoptim/data/xrrData.rda
/usr/lib64/R/library/DEoptim/demo/DEoptim.R
/usr/lib64/R/library/DEoptim/demo/benchmarks.R
/usr/lib64/R/library/DEoptim/doc/DEoptim.R
/usr/lib64/R/library/DEoptim/doc/DEoptim.Rnw
/usr/lib64/R/library/DEoptim/doc/DEoptim.pdf
/usr/lib64/R/library/DEoptim/doc/DEoptimPortfolioOptimization.Rnw
/usr/lib64/R/library/DEoptim/doc/DEoptimPortfolioOptimization.pdf
/usr/lib64/R/library/DEoptim/doc/index.html
/usr/lib64/R/library/DEoptim/help/AnIndex
/usr/lib64/R/library/DEoptim/help/DEoptim.rdb
/usr/lib64/R/library/DEoptim/help/DEoptim.rdx
/usr/lib64/R/library/DEoptim/help/aliases.rds
/usr/lib64/R/library/DEoptim/help/paths.rds
/usr/lib64/R/library/DEoptim/html/00Index.html
/usr/lib64/R/library/DEoptim/html/R.css
/usr/lib64/R/library/DEoptim/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/DEoptim/libs/DEoptim.so
/usr/lib64/R/library/DEoptim/libs/DEoptim.so.avx2
/usr/lib64/R/library/DEoptim/libs/DEoptim.so.avx512
